-- MySQL Script generated by MySQL Workbench
-- Fri Jun 11 03:32:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RaportMed
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `RaportMed` ;

-- -----------------------------------------------------
-- Schema RaportMed
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RaportMed` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `RaportMed` ;

-- -----------------------------------------------------
-- Table `Consultation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Consultation` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Consultation` (
  `idC` INT NOT NULL AUTO_INCREMENT,
  `Diagnostic` VARCHAR(45) NOT NULL,
  `Mount` FLOAT NULL,
  `Patient_idP` INT NOT NULL,
  `Doctor_idDoctor` INT NOT NULL,
  PRIMARY KEY (`idC`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Departement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Departement` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Departement` (
  `idDepartement` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Hopital_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDepartement`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Doctor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Doctor` (
  `idDoctor` INT NOT NULL AUTO_INCREMENT,
  `Departement_idDepartement` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `TimeB` VARCHAR(45) NULL,
  `Doctorcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idDoctor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Hopital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hopital` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Hopital` (
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Medicament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Medicament` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Medicament` (
  `idM` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idM`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Patient` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Patient` (
  `idP` INT NOT NULL AUTO_INCREMENT,
  `Appoint` DATE NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idP`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Raport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Raport` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Raport` (
  `Consultation_idC` INT NOT NULL,
  `Medicament_idM` INT NOT NULL,
  PRIMARY KEY (`Consultation_idC`, `Medicament_idM`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Mobile_N` INT NULL,
  `Sexe` ENUM('F', 'M') NULL,
  `Adresse` VARCHAR(45) NULL,
  `Groupage` ENUM('A+', 'A-', 'B-', 'B+', 'AB+', 'AB-', 'O+', 'O-') NULL,
  `Age` INT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
